name: Go
on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Get dependencies
      run: go mod download
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
    - name: Test
      run: go test -v ./...
